
remote_theme: mmistakes/so-simple-theme

locale: en-US
title: "Yassine"
description: "A(nother) Machine Learning Blog"
baseurl: "/ml-blog"
url: "https://yassouali.github.io/"

# Images 
logo: "/images/logo.png"
favicon: "/images/favicon.ico"

header_logo: "/images/header_logo.png"

date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
  - name: "Livvic"
    weights: "400,400i,700,700i"
google_analytics: "UA-156247515-1"
disqus:
  shortname: "https-yassouali-github-io"
twitter:
  username: "yass_ouali"
google_site_verification: "UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8Y"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 5
# paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

# Collections
collections:
  personal:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true

  # Personnal Posts
  - scope:
      path: "_personal"
      type: personal
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: Yassine #Ouali
  picture: 
  email: ouali.yasine@gmail.com
  twitter: mmistakes
  links:
    - title: Twitter
      url: https://twitter.com/yass_ouali
      icon: fab fa-twitter-square
    - title: Instagram
      url: https://www.instagram.com/yas_ouali/
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/yassouali
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/yass_ouali
    icon: fab fa-twitter-square
  #- title: Instagram
  #  url: https://www.instagram.com/yas_ouali/
  #  icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/yassouali
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
